name: Test docker images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ROOT_TUTORIAL_PATH: /opt/root/6.36.04/cxx20/tutorials

jobs:
  test-docker-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - "ghcr.io/zhao-shihan/rgb-docker"
          - "ghcr.io/zhao-shihan/rgb-docker:slim"
          - "ghcr.io/zhao-shihan/rgb-docker:mpich"
          - "ghcr.io/zhao-shihan/rgb-docker:mpich-slim"
          - "ghcr.io/zhao-shihan/rgb-docker:openmpi"
          - "ghcr.io/zhao-shihan/rgb-docker:openmpi-slim"
          - "ghcr.io/zhao-shihan/rgb-docker:latest"
          - "ghcr.io/zhao-shihan/rgb-docker:latest-slim"
          - "ghcr.io/zhao-shihan/rgb-docker:latest-mpich"
          - "ghcr.io/zhao-shihan/rgb-docker:latest-mpich-slim"
          - "ghcr.io/zhao-shihan/rgb-docker:latest-openmpi"
          - "ghcr.io/zhao-shihan/rgb-docker:latest-openmpi-slim"
          - "ghcr.io/zhao-shihan/rgb-docker:25.10.14"
          - "ghcr.io/zhao-shihan/rgb-docker:25.10.14-slim"
          - "ghcr.io/zhao-shihan/rgb-docker:25.10.14-mpich"
          - "ghcr.io/zhao-shihan/rgb-docker:25.10.14-mpich-slim"
          - "ghcr.io/zhao-shihan/rgb-docker:25.10.14-openmpi"
          - "ghcr.io/zhao-shihan/rgb-docker:25.10.14-openmpi-slim"

    container: ${{ matrix.image }}

    name: Test ${{ matrix.image }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Check MPI config
        run: |
          . /environment
          mpirun --version
          mpiexec --version
          mpicc -v
          mpic++ -v
          mpicxx -v
          mpifort -v
          mpif77 -v
          mpif90 -v

      - name: Test MPI
        run: |
          . /environment
          lscpu
          mkdir test-mpi && cd test-mpi
          git clone https://github.com/LLNL/mpiBench.git
          cd mpiBench
          make
          mpiexec -n 4 ./mpiBench || mpiexec --allow-run-as-root -n 4 ./mpiBench

      - name: Check ROOT config
        run: |
          . /environment
          root-config --prefix
          root-config --cc
          root-config --cxx
          root-config --version
          root-config --features
          root-config --config

      - name: Test ROOT
        run: |
          . /environment
          root -l -q ${ROOT_TUTORIAL_PATH}/hsimple.C
          python ${ROOT_TUTORIAL_PATH}/hsimple.C
          root -l -q ${ROOT_TUTORIAL_PATH}/math/mathmoreIntegration.C
          root -l -q ${ROOT_TUTORIAL_PATH}/roofit/roofit/rf801_mcstudy.C
          python ${ROOT_TUTORIAL_PATH}/roofit/roofit/rf801_mcstudy.py

      - name: Check Geant4 config
        run: |
          . /environment
          geant4-config --prefix
          geant4-config --version
          geant4-config --libs
          geant4-config --cflags

      - name: Test Geant4
        run: |
          . /environment
          geant4-config --prefix
          geant4-config --version
          geant4-config --libs
          geant4-config --cflags
