name: Test docker images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  VERSION: 25.10.14
  ROOT_TUTORIAL_PATH: /opt/root/6.36.04/cxx20/tutorials

jobs:
  test-docker-images:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        image:
          - "ghcr.io/zhao-shihan/rgb-docker"
          - "ghcr.io/zhao-shihan/rgb-docker:slim"
          - "ghcr.io/zhao-shihan/rgb-docker:mpich"
          - "ghcr.io/zhao-shihan/rgb-docker:mpich-slim"
          - "ghcr.io/zhao-shihan/rgb-docker:openmpi"
          - "ghcr.io/zhao-shihan/rgb-docker:openmpi-slim"
          - "ghcr.io/zhao-shihan/rgb-docker:latest"
          - "ghcr.io/zhao-shihan/rgb-docker:latest-slim"
          - "ghcr.io/zhao-shihan/rgb-docker:latest-mpich"
          - "ghcr.io/zhao-shihan/rgb-docker:latest-mpich-slim"
          - "ghcr.io/zhao-shihan/rgb-docker:latest-openmpi"
          - "ghcr.io/zhao-shihan/rgb-docker:latest-openmpi-slim"
          - "ghcr.io/zhao-shihan/rgb-docker:${{ steps.vars.outputs.version }}"
          - "ghcr.io/zhao-shihan/rgb-docker:${{ steps.vars.outputs.version }}-slim"
          - "ghcr.io/zhao-shihan/rgb-docker:${{ steps.vars.outputs.version }}-mpich"
          - "ghcr.io/zhao-shihan/rgb-docker:${{ steps.vars.outputs.version }}-mpich-slim"
          - "ghcr.io/zhao-shihan/rgb-docker:${{ steps.vars.outputs.version }}-openmpi"
          - "ghcr.io/zhao-shihan/rgb-docker:${{ steps.vars.outputs.version }}-openmpi-slim"

    container: ${{ matrix.image }}

    name: Test ${{ matrix.image }}

    steps:
      - name: Set dynamic variables
        id: vars
        run: |
          echo "::set-output name=version::${VERSION}"
  
      - name: Check MPI config
        run: |
          mpirun --version
          mpiexec --version
          mpicc -v
          mpic++ -v
          mpicxx -v
          mpifort -v
          mpif77 -v
          mpif90 -v

      - name: Test MPI
        run: |
          mkdir test-mpi && cd test-mpi
          git clone https://github.com/LLNL/mpiBench.git
          cd mpiBench
          make
          mpiexec -n 4 ./mpiBench

      - name: Check ROOT config
        run: |
          root-config --prefix
          root-config --cc
          root-config --cxx
          root-config --version
          root-config --features
          root-config --config

      - name: Test ROOT
        run: |
          root -l -q ${ROOT_TUTORIAL_PATH}/hsimple.C
          python ${ROOT_TUTORIAL_PATH}/hsimple.C
          root -l -q ${ROOT_TUTORIAL_PATH}/math/mathmoreIntegration.C
          root -l -q ${ROOT_TUTORIAL_PATH}/roofit/roofit/rf801_mcstudy.C
          python ${ROOT_TUTORIAL_PATH}/roofit/roofit/rf801_mcstudy.py

      - name: Check Geant4 config
        run: |
          geant4-config --prefix
          geant4-config --version
          geant4-config --libs
          geant4-config --cflags

      - name: Test Geant4
        run: |
          geant4-config --prefix
          geant4-config --version
          geant4-config --libs
          geant4-config --cflags
