name: Test docker images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-docker-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - "ghcr.io/zhao-shihan/rgb-docker"
          - "ghcr.io/zhao-shihan/rgb-docker:mpich"
          - "ghcr.io/zhao-shihan/rgb-docker:mpich-slim"
          - "ghcr.io/zhao-shihan/rgb-docker:openmpi"
          - "ghcr.io/zhao-shihan/rgb-docker:openmpi-slim"
          - "ghcr.io/zhao-shihan/rgb-docker:latest"
          - "ghcr.io/zhao-shihan/rgb-docker:latest-mpich"
          - "ghcr.io/zhao-shihan/rgb-docker:latest-mpich-slim"
          - "ghcr.io/zhao-shihan/rgb-docker:latest-openmpi"
          - "ghcr.io/zhao-shihan/rgb-docker:latest-openmpi-slim"

    container: ${{ matrix.image }}

    name: Test ${{ matrix.image }}

    steps:
      - name: Check MPI config
        run: mpirun --version

      - name: Check ROOT config
        run: |
          root-config --prefix
          root-config --cc
          root-config --cxx
          root-config --version
          root-config --features
          root-config --config

      - name: Check Geant4 config
        run: |
          geant4-config --prefix
          geant4-config --version
          geant4-config --libs
          geant4-config --cflags
